[package]
name = "dataset"
version = "0.1.0"
edition = "2021"

[lib]
name = "ink_trace_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"
rand = "0.8"
rayon = "1.8"
